const characters = [
    // Dragon Ball (1986)
    {
        name: "Son Goku",
        anime: "Dragon Ball",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 1986,
    },
    {
        name: "Bulma",
        anime: "Dragon Ball",
        gender: "Female",
        hairColor: "Blue",
        firstAppearanceYear: 1986,
    },
    {
        name: "Krillin",
        anime: "Dragon Ball",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 1986,
    },
    {
        name: "Master Roshi",
        anime: "Dragon Ball",
        gender: "Male",
        hairColor: "White",
        firstAppearanceYear: 1986,
    },
    {
        name: "Yamcha",
        anime: "Dragon Ball",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 1986,
    },
    {
        name: "Piccolo",
        anime: "Dragon Ball",
        gender: "Male",
        hairColor: "None",
        firstAppearanceYear: 1986,
    },
    // Dragon Ball Z (1989)
    {
        name: "Vegeta",
        anime: "Dragon Ball Z",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 1989,
    },
    {
        name: "Son Gohan",
        anime: "Dragon Ball Z",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 1989,
    },
    {
        name: "Frieza",
        anime: "Dragon Ball Z",
        gender: "Male",
        hairColor: "None",
        firstAppearanceYear: 1989,
    },
    {
        name: "Trunks (Future)",
        anime: "Dragon Ball Z",
        gender: "Male",
        hairColor: "Purple",
        firstAppearanceYear: 1989,
    },
    {
        name: "Cell",
        anime: "Dragon Ball Z",
        gender: "Male",
        hairColor: "None",
        firstAppearanceYear: 1989,
    },
    {
        name: "Majin Buu",
        anime: "Dragon Ball Z",
        gender: "Male",
        hairColor: "None",
        firstAppearanceYear: 1989,
    },
    {
        name: "Android 18",
        anime: "Dragon Ball Z",
        gender: "Female",
        hairColor: "Blonde",
        firstAppearanceYear: 1989,
    },
    // Saint Seiya (1986)
    {
        name: "Pegasus Seiya",
        anime: "Saint Seiya",
        gender: "Male",
        hairColor: "Brown",
        firstAppearanceYear: 1986,
    },
    {
        name: "Dragon Shiryu",
        anime: "Saint Seiya",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 1986,
    },
    {
        name: "Cygnus Hyoga",
        anime: "Saint Seiya",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 1986,
    },
    {
        name: "Andromeda Shun",
        anime: "Saint Seiya",
        gender: "Male",
        hairColor: "Green",
        firstAppearanceYear: 1986,
    },
    {
        name: "Phoenix Ikki",
        anime: "Saint Seiya",
        gender: "Male",
        hairColor: "Blue",
        firstAppearanceYear: 1986,
    },
    {
        name: "Saori Kido (Athena)",
        anime: "Saint Seiya",
        gender: "Female",
        hairColor: "Purple",
        firstAppearanceYear: 1986,
    },
    // Yu Yu Hakusho (1992)
    {
        name: "Yusuke Urameshi",
        anime: "Yu Yu Hakusho",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 1992,
    },
    {
        name: "Kazuma Kuwabara",
        anime: "Yu Yu Hakusho",
        gender: "Male",
        hairColor: "Orange",
        firstAppearanceYear: 1992,
    },
    {
        name: "Kurama",
        anime: "Yu Yu Hakusho",
        gender: "Male",
        hairColor: "Red",
        firstAppearanceYear: 1992,
    },
    {
        name: "Hiei",
        anime: "Yu Yu Hakusho",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 1992,
    },
    {
        name: "Genkai",
        anime: "Yu Yu Hakusho",
        gender: "Female",
        hairColor: "Pink",
        firstAppearanceYear: 1992,
    },
    // Sailor Moon (1992)
    {
        name: "Usagi Tsukino (Sailor Moon)",
        anime: "Sailor Moon",
        gender: "Female",
        hairColor: "Blonde",
        firstAppearanceYear: 1992,
    },
    {
        name: "Ami Mizuno (Sailor Mercury)",
        anime: "Sailor Moon",
        gender: "Female",
        hairColor: "Blue",
        firstAppearanceYear: 1992,
    },
    {
        name: "Rei Hino (Sailor Mars)",
        anime: "Sailor Moon",
        gender: "Female",
        hairColor: "Black",
        firstAppearanceYear: 1992,
    },
    {
        name: "Makoto Kino (Sailor Jupiter)",
        anime: "Sailor Moon",
        gender: "Female",
        hairColor: "Brown",
        firstAppearanceYear: 1992,
    },
    {
        name: "Minako Aino (Sailor Venus)",
        anime: "Sailor Moon",
        gender: "Female",
        hairColor: "Blonde",
        firstAppearanceYear: 1992,
    },
    {
        name: "Mamoru Chiba (Tuxedo Mask)",
        anime: "Sailor Moon",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 1992,
    },
    // Slam Dunk (1993)
    {
        name: "Hanamichi Sakuragi",
        anime: "Slam Dunk",
        gender: "Male",
        hairColor: "Red",
        firstAppearanceYear: 1993,
    },
    {
        name: "Kaede Rukawa",
        anime: "Slam Dunk",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 1993,
    },
    {
        name: "Hisashi Mitsui",
        anime: "Slam Dunk",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 1993,
    },
    {
        name: "Ryota Miyagi",
        anime: "Slam Dunk",
        gender: "Male",
        hairColor: "Brown",
        firstAppearanceYear: 1993,
    },
    {
        name: "Takenori Akagi",
        anime: "Slam Dunk",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 1993,
    },
    // Neon Genesis Evangelion (1995)
    {
        name: "Shinji Ikari",
        anime: "Neon Genesis Evangelion",
        gender: "Male",
        hairColor: "Brown",
        firstAppearanceYear: 1995,
    },
    {
        name: "Rei Ayanami",
        anime: "Neon Genesis Evangelion",
        gender: "Female",
        hairColor: "Blue",
        firstAppearanceYear: 1995,
    },
    {
        name: "Asuka Langley Soryu",
        anime: "Neon Genesis Evangelion",
        gender: "Female",
        hairColor: "Red",
        firstAppearanceYear: 1995,
    },
    {
        name: "Misato Katsuragi",
        anime: "Neon Genesis Evangelion",
        gender: "Female",
        hairColor: "Purple",
        firstAppearanceYear: 1995,
    },
    {
        name: "Kaworu Nagisa",
        anime: "Neon Genesis Evangelion",
        gender: "Male",
        hairColor: "White",
        firstAppearanceYear: 1995,
    },
    // Rurouni Kenshin (1996)
    {
        name: "Kenshin Himura",
        anime: "Rurouni Kenshin",
        gender: "Male",
        hairColor: "Red",
        firstAppearanceYear: 1996,
    },
    {
        name: "Kaoru Kamiya",
        anime: "Rurouni Kenshin",
        gender: "Female",
        hairColor: "Black",
        firstAppearanceYear: 1996,
    },
    {
        name: "Sanosuke Sagara",
        anime: "Rurouni Kenshin",
        gender: "Male",
        hairColor: "Brown",
        firstAppearanceYear: 1996,
    },
    {
        name: "Yahiko Myojin",
        anime: "Rurouni Kenshin",
        gender: "Male",
        hairColor: "Brown",
        firstAppearanceYear: 1996,
    },
    {
        name: "Makoto Shishio",
        anime: "Rurouni Kenshin",
        gender: "Male",
        hairColor: "None",
        firstAppearanceYear: 1996,
    },
    // Pokémon (1997)
    {
        name: "Ash Ketchum (Satoshi)",
        anime: "Pokémon",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 1997,
    },
    {
        name: "Pikachu",
        anime: "Pokémon",
        gender: "Male",
        hairColor: "Yellow",
        firstAppearanceYear: 1997,
    },
    {
        name: "Misty (Kasumi)",
        anime: "Pokémon",
        gender: "Female",
        hairColor: "Orange",
        firstAppearanceYear: 1997,
    },
    {
        name: "Brock (Takeshi)",
        anime: "Pokémon",
        gender: "Male",
        hairColor: "Brown",
        firstAppearanceYear: 1997,
    },
    {
        name: "Jessie (Musashi)",
        anime: "Pokémon",
        gender: "Female",
        hairColor: "Magenta",
        firstAppearanceYear: 1997,
    },
    {
        name: "James (Kojiro)",
        anime: "Pokémon",
        gender: "Male",
        hairColor: "Purple",
        firstAppearanceYear: 1997,
    },
    // Cowboy Bebop (1998)
    {
        name: "Spike Spiegel",
        anime: "Cowboy Bebop",
        gender: "Male",
        hairColor: "Green",
        firstAppearanceYear: 1998,
    },
    {
        name: "Faye Valentine",
        anime: "Cowboy Bebop",
        gender: "Female",
        hairColor: "Purple",
        firstAppearanceYear: 1998,
    },
    {
        name: "Jet Black",
        anime: "Cowboy Bebop",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 1998,
    },
    {
        name: "Edward Wong Hau Pepelu Tivrusky IV",
        anime: "Cowboy Bebop",
        gender: "Female",
        hairColor: "Red",
        firstAppearanceYear: 1998,
    },
    // One Piece (1999)
    {
        name: "Monkey D. Luffy",
        anime: "One Piece",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 1999,
    },
    {
        name: "Roronoa Zoro",
        anime: "One Piece",
        gender: "Male",
        hairColor: "Green",
        firstAppearanceYear: 1999,
    },
    {
        name: "Nami",
        anime: "One Piece",
        gender: "Female",
        hairColor: "Orange",
        firstAppearanceYear: 1999,
    },
    {
        name: "Usopp",
        anime: "One Piece",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 1999,
    },
    {
        name: "Sanji",
        anime: "One Piece",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 1999,
    },
    {
        name: "Tony Tony Chopper",
        anime: "One Piece",
        gender: "Male",
        hairColor: "Brown",
        firstAppearanceYear: 1999,
    },
    {
        name: "Nico Robin",
        anime: "One Piece",
        gender: "Female",
        hairColor: "Black",
        firstAppearanceYear: 1999,
    },
    {
        name: "Franky",
        anime: "One Piece",
        gender: "Male",
        hairColor: "Blue",
        firstAppearanceYear: 1999,
    },
    {
        name: "Brook",
        anime: "One Piece",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 1999,
    },
    {
        name: "Jinbe",
        anime: "One Piece",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 1999,
    },
    {
        name: "Portgas D. Ace",
        anime: "One Piece",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 1999,
    },
    {
        name: "Trafalgar D. Water Law",
        anime: "One Piece",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 1999,
    },
    {
        name: "Boa Hancock",
        anime: "One Piece",
        gender: "Female",
        hairColor: "Black",
        firstAppearanceYear: 1999,
    },
    {
        name: "Shanks",
        anime: "One Piece",
        gender: "Male",
        hairColor: "Red",
        firstAppearanceYear: 1999,
    },
    {
        name: "Dracule Mihawk",
        anime: "One Piece",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 1999,
    },
    // Hunter x Hunter (1999)
    {
        name: "Gon Freecss",
        anime: "Hunter x Hunter",
        gender: "Male",
        hairColor: "Green",
        firstAppearanceYear: 1999,
    },
    {
        name: "Killua Zoldyck",
        anime: "Hunter x Hunter",
        gender: "Male",
        hairColor: "White",
        firstAppearanceYear: 1999,
    },
    {
        name: "Kurapika",
        anime: "Hunter x Hunter",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 1999,
    },
    {
        name: "Leorio Paradinight",
        anime: "Hunter x Hunter",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 1999,
    },
    {
        name: "Hisoka Morow",
        anime: "Hunter x Hunter",
        gender: "Male",
        hairColor: "Red",
        firstAppearanceYear: 1999,
    },
    // InuYasha (2000)
    {
        name: "Inuyasha",
        anime: "InuYasha",
        gender: "Male",
        hairColor: "White",
        firstAppearanceYear: 2000,
    },
    {
        name: "Kagome Higurashi",
        anime: "InuYasha",
        gender: "Female",
        hairColor: "Black",
        firstAppearanceYear: 2000,
    },
    {
        name: "Sesshomaru",
        anime: "InuYasha",
        gender: "Male",
        hairColor: "White",
        firstAppearanceYear: 2000,
    },
    {
        name: "Sango",
        anime: "InuYasha",
        gender: "Female",
        hairColor: "Brown",
        firstAppearanceYear: 2000,
    },
    {
        name: "Miroku",
        anime: "InuYasha",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2000,
    },
    // Naruto (2002)
    {
        name: "Naruto Uzumaki",
        anime: "Naruto",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2002,
    },
    {
        name: "Sasuke Uchiha",
        anime: "Naruto",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2002,
    },
    {
        name: "Sakura Haruno",
        anime: "Naruto",
        gender: "Female",
        hairColor: "Pink",
        firstAppearanceYear: 2002,
    },
    {
        name: "Kakashi Hatake",
        anime: "Naruto",
        gender: "Male",
        hairColor: "White",
        firstAppearanceYear: 2002,
    },
    {
        name: "Hinata Hyuga",
        anime: "Naruto",
        gender: "Female",
        hairColor: "Blue",
        firstAppearanceYear: 2002,
    },
    {
        name: "Gaara",
        anime: "Naruto",
        gender: "Male",
        hairColor: "Red",
        firstAppearanceYear: 2002,
    },
    {
        name: "Shikamaru Nara",
        anime: "Naruto",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2002,
    },
    {
        name: "Rock Lee",
        anime: "Naruto",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2002,
    },
    {
        name: "Jiraiya",
        anime: "Naruto",
        gender: "Male",
        hairColor: "White",
        firstAppearanceYear: 2002,
    },
    {
        name: "Itachi Uchiha",
        anime: "Naruto",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2002,
    },
    // Fullmetal Alchemist (2003)
    {
        name: "Edward Elric",
        anime: "Fullmetal Alchemist",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2003,
    },
    {
        name: "Alphonse Elric",
        anime: "Fullmetal Alchemist",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2003,
    },
    {
        name: "Roy Mustang",
        anime: "Fullmetal Alchemist",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2003,
    },
    {
        name: "Winry Rockbell",
        anime: "Fullmetal Alchemist",
        gender: "Female",
        hairColor: "Blonde",
        firstAppearanceYear: 2003,
    },
    {
        name: "Riza Hawkeye",
        anime: "Fullmetal Alchemist",
        gender: "Female",
        hairColor: "Blonde",
        firstAppearanceYear: 2003,
    },
    // Bleach (2004)
    {
        name: "Ichigo Kurosaki",
        anime: "Bleach",
        gender: "Male",
        hairColor: "Orange",
        firstAppearanceYear: 2004,
    },
    {
        name: "Rukia Kuchiki",
        anime: "Bleach",
        gender: "Female",
        hairColor: "Black",
        firstAppearanceYear: 2004,
    },
    {
        name: "Orihime Inoue",
        anime: "Bleach",
        gender: "Female",
        hairColor: "Orange",
        firstAppearanceYear: 2004,
    },
    {
        name: "Uryu Ishida",
        anime: "Bleach",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2004,
    },
    {
        name: "Yasutora Sado (Chad)",
        anime: "Bleach",
        gender: "Male",
        hairColor: "Brown",
        firstAppearanceYear: 2004,
    },
    {
        name: "Renji Abarai",
        anime: "Bleach",
        gender: "Male",
        hairColor: "Red",
        firstAppearanceYear: 2004,
    },
    {
        name: "Toshiro Hitsugaya",
        anime: "Bleach",
        gender: "Male",
        hairColor: "White",
        firstAppearanceYear: 2004,
    },
    {
        name: "Kenpachi Zaraki",
        anime: "Bleach",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2004,
    },
    {
        name: "Byakuya Kuchiki",
        anime: "Bleach",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2004,
    },
    {
        name: "Sosuke Aizen",
        anime: "Bleach",
        gender: "Male",
        hairColor: "Brown",
        firstAppearanceYear: 2004,
    },
    {
        name: "Ulquiorra Cifer",
        anime: "Bleach",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2004,
    },
    {
        name: "Grimmjow Jaegerjaquez",
        anime: "Bleach",
        gender: "Male",
        hairColor: "Blue",
        firstAppearanceYear: 2004,
    },
    // Gintama (2006)
    {
        name: "Gintoki Sakata",
        anime: "Gintama",
        gender: "Male",
        hairColor: "Silver",
        firstAppearanceYear: 2006,
    },
    {
        name: "Shinpachi Shimura",
        anime: "Gintama",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2006,
    },
    {
        name: "Kagura",
        anime: "Gintama",
        gender: "Female",
        hairColor: "Red",
        firstAppearanceYear: 2006,
    },
    {
        name: "Toshiro Hijikata",
        anime: "Gintama",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2006,
    },
    {
        name: "Sougo Okita",
        anime: "Gintama",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2006,
    },
    {
        name: "Kotaro Katsura",
        anime: "Gintama",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2006,
    },
    // Death Note (2006)
    {
        name: "Light Yagami",
        anime: "Death Note",
        gender: "Male",
        hairColor: "Brown",
        firstAppearanceYear: 2006,
    },
    {
        name: "L Lawliet",
        anime: "Death Note",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2006,
    },
    {
        name: "Misa Amane",
        anime: "Death Note",
        gender: "Female",
        hairColor: "Blonde",
        firstAppearanceYear: 2006,
    },
    {
        name: "Ryuk",
        anime: "Death Note",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2006,
    },
    // Code Geass (2006)
    {
        name: "Lelouch vi Britannia",
        anime: "Code Geass",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2006,
    },
    {
        name: "C.C.",
        anime: "Code Geass",
        gender: "Female",
        hairColor: "Green",
        firstAppearanceYear: 2006,
    },
    {
        name: "Suzaku Kururugi",
        anime: "Code Geass",
        gender: "Male",
        hairColor: "Brown",
        firstAppearanceYear: 2006,
    },
    {
        name: "Kallen Kozuki",
        anime: "Code Geass",
        gender: "Female",
        hairColor: "Red",
        firstAppearanceYear: 2006,
    },
    // Gurren Lagann (2007)
    {
        name: "Simon",
        anime: "Gurren Lagann",
        gender: "Male",
        hairColor: "Blue",
        firstAppearanceYear: 2007,
    },
    {
        name: "Kamina",
        anime: "Gurren Lagann",
        gender: "Male",
        hairColor: "Blue",
        firstAppearanceYear: 2007,
    },
    {
        name: "Yoko Littner",
        anime: "Gurren Lagann",
        gender: "Female",
        hairColor: "Red",
        firstAppearanceYear: 2007,
    },
    {
        name: "Nia Teppelin",
        anime: "Gurren Lagann",
        gender: "Female",
        hairColor: "Blonde",
        firstAppearanceYear: 2007,
    },
    // Soul Eater (2008)
    {
        name: "Maka Albarn",
        anime: "Soul Eater",
        gender: "Female",
        hairColor: "Blonde",
        firstAppearanceYear: 2008,
    },
    {
        name: "Soul Evans",
        anime: "Soul Eater",
        gender: "Male",
        hairColor: "White",
        firstAppearanceYear: 2008,
    },
    {
        name: "Black Star",
        anime: "Soul Eater",
        gender: "Male",
        hairColor: "Blue",
        firstAppearanceYear: 2008,
    },
    {
        name: "Death the Kid",
        anime: "Soul Eater",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2008,
    },
    // Fairy Tail (2009)
    {
        name: "Natsu Dragneel",
        anime: "Fairy Tail",
        gender: "Male",
        hairColor: "Pink",
        firstAppearanceYear: 2009,
    },
    {
        name: "Lucy Heartfilia",
        anime: "Fairy Tail",
        gender: "Female",
        hairColor: "Blonde",
        firstAppearanceYear: 2009,
    },
    {
        name: "Gray Fullbuster",
        anime: "Fairy Tail",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2009,
    },
    {
        name: "Erza Scarlet",
        anime: "Fairy Tail",
        gender: "Female",
        hairColor: "Red",
        firstAppearanceYear: 2009,
    },
    {
        name: "Wendy Marvell",
        anime: "Fairy Tail",
        gender: "Female",
        hairColor: "Blue",
        firstAppearanceYear: 2009,
    },
    // Steins;Gate (2011)
    {
        name: "Rintaro Okabe",
        anime: "Steins;Gate",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2011,
    },
    {
        name: "Kurisu Makise",
        anime: "Steins;Gate",
        gender: "Female",
        hairColor: "Red",
        firstAppearanceYear: 2011,
    },
    {
        name: "Mayuri Shiina",
        anime: "Steins;Gate",
        gender: "Female",
        hairColor: "Black",
        firstAppearanceYear: 2011,
    },
    {
        name: "Itaru Hashida",
        anime: "Steins;Gate",
        gender: "Male",
        hairColor: "Brown",
        firstAppearanceYear: 2011,
    },
    // Puella Magi Madoka Magica (2011)
    {
        name: "Madoka Kaname",
        anime: "Puella Magi Madoka Magica",
        gender: "Female",
        hairColor: "Pink",
        firstAppearanceYear: 2011,
    },
    {
        name: "Homura Akemi",
        anime: "Puella Magi Madoka Magica",
        gender: "Female",
        hairColor: "Black",
        firstAppearanceYear: 2011,
    },
    {
        name: "Sayaka Miki",
        anime: "Puella Magi Madoka Magica",
        gender: "Female",
        hairColor: "Blue",
        firstAppearanceYear: 2011,
    },
    {
        name: "Kyoko Sakura",
        anime: "Puella Magi Madoka Magica",
        gender: "Female",
        hairColor: "Red",
        firstAppearanceYear: 2011,
    },
    {
        name: "Mami Tomoe",
        anime: "Puella Magi Madoka Magica",
        gender: "Female",
        hairColor: "Blonde",
        firstAppearanceYear: 2011,
    },
    {
        name: "Kyubey",
        anime: "Puella Magi Madoka Magica",
        gender: "Male",
        hairColor: "White",
        firstAppearanceYear: 2011,
    },
    // Sword Art Online (2012)
    {
        name: "Kirito (Kazuto Kirigaya)",
        anime: "Sword Art Online",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2012,
    },
    {
        name: "Asuna (Asuna Yuuki)",
        anime: "Sword Art Online",
        gender: "Female",
        hairColor: "Orange",
        firstAppearanceYear: 2012,
    },
    {
        name: "Sinon (Shino Asada)",
        anime: "Sword Art Online",
        gender: "Female",
        hairColor: "Blue",
        firstAppearanceYear: 2012,
    },
    {
        name: "Yui",
        anime: "Sword Art Online",
        gender: "Female",
        hairColor: "Black",
        firstAppearanceYear: 2012,
    },
    // JoJo's Bizarre Adventure (2012)
    {
        name: "Jonathan Joestar",
        anime: "JoJo's Bizarre Adventure",
        gender: "Male",
        hairColor: "Blue",
        firstAppearanceYear: 2012,
    },
    {
        name: "Dio Brando",
        anime: "JoJo's Bizarre Adventure",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2012,
    },
    {
        name: "Joseph Joestar",
        anime: "JoJo's Bizarre Adventure",
        gender: "Male",
        hairColor: "Brown",
        firstAppearanceYear: 2012,
    },
    {
        name: "Jotaro Kujo",
        anime: "JoJo's Bizarre Adventure",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2012,
    },
    {
        name: "Josuke Higashikata",
        anime: "JoJo's Bizarre Adventure",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2012,
    },
    {
        name: "Giorno Giovanna",
        anime: "JoJo's Bizarre Adventure",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2012,
    },
    {
        name: "Jolyne Cujoh",
        anime: "JoJo's Bizarre Adventure",
        gender: "Female",
        hairColor: "Green",
        firstAppearanceYear: 2012,
    },
    {
        name: "Rohan Kishibe",
        anime: "JoJo's Bizarre Adventure",
        gender: "Male",
        hairColor: "Green",
        firstAppearanceYear: 2012,
    },
    {
        name: "Jean Pierre Polnareff",
        anime: "JoJo's Bizarre Adventure",
        gender: "Male",
        hairColor: "White",
        firstAppearanceYear: 2012,
    },
    {
        name: "Noriaki Kakyoin",
        anime: "JoJo's Bizarre Adventure",
        gender: "Male",
        hairColor: "Red",
        firstAppearanceYear: 2012,
    },
    // Attack on Titan (2013)
    {
        name: "Eren Yeager",
        anime: "Attack on Titan",
        gender: "Male",
        hairColor: "Brown",
        firstAppearanceYear: 2013,
    },
    {
        name: "Mikasa Ackerman",
        anime: "Attack on Titan",
        gender: "Female",
        hairColor: "Black",
        firstAppearanceYear: 2013,
    },
    {
        name: "Armin Arlert",
        anime: "Attack on Titan",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2013,
    },
    {
        name: "Levi Ackerman",
        anime: "Attack on Titan",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2013,
    },
    {
        name: "Erwin Smith",
        anime: "Attack on Titan",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2013,
    },
    {
        name: "Hange Zoë",
        anime: "Attack on Titan",
        gender: "Non-binary",
        hairColor: "Brown",
        firstAppearanceYear: 2013,
    },
    {
        name: "Reiner Braun",
        anime: "Attack on Titan",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2013,
    },
    {
        name: "Sasha Blouse",
        anime: "Attack on Titan",
        gender: "Female",
        hairColor: "Brown",
        firstAppearanceYear: 2013,
    },
    // Haikyuu!! (2014)
    {
        name: "Shoyo Hinata",
        anime: "Haikyuu!!",
        gender: "Male",
        hairColor: "Orange",
        firstAppearanceYear: 2014,
    },
    {
        name: "Tobio Kageyama",
        anime: "Haikyuu!!",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2014,
    },
    {
        name: "Kei Tsukishima",
        anime: "Haikyuu!!",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2014,
    },
    {
        name: "Toru Oikawa",
        anime: "Haikyuu!!",
        gender: "Male",
        hairColor: "Brown",
        firstAppearanceYear: 2014,
    },
    {
        name: "Kenma Kozume",
        anime: "Haikyuu!!",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2014,
    },
    // Tokyo Ghoul (2014)
    {
        name: "Ken Kaneki",
        anime: "Tokyo Ghoul",
        gender: "Male",
        hairColor: "White",
        firstAppearanceYear: 2014,
    },
    {
        name: "Touka Kirishima",
        anime: "Tokyo Ghoul",
        gender: "Female",
        hairColor: "Purple",
        firstAppearanceYear: 2014,
    },
    {
        name: "Juuzou Suzuya",
        anime: "Tokyo Ghoul",
        gender: "Male",
        hairColor: "White",
        firstAppearanceYear: 2014,
    },
    // The Seven Deadly Sins (2014)
    {
        name: "Meliodas",
        anime: "The Seven Deadly Sins",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2014,
    },
    {
        name: "Elizabeth Liones",
        anime: "The Seven Deadly Sins",
        gender: "Female",
        hairColor: "Silver",
        firstAppearanceYear: 2014,
    },
    {
        name: "Ban",
        anime: "The Seven Deadly Sins",
        gender: "Male",
        hairColor: "Blue",
        firstAppearanceYear: 2014,
    },
    {
        name: "King",
        anime: "The Seven Deadly Sins",
        gender: "Male",
        hairColor: "Brown",
        firstAppearanceYear: 2014,
    },
    {
        name: "Diane",
        anime: "The Seven Deadly Sins",
        gender: "Female",
        hairColor: "Brown",
        firstAppearanceYear: 2014,
    },
    // One-Punch Man (2015)
    {
        name: "Saitama",
        anime: "One-Punch Man",
        gender: "Male",
        hairColor: "None",
        firstAppearanceYear: 2015,
    },
    {
        name: "Genos",
        anime: "One-Punch Man",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2015,
    },
    {
        name: "Tatsumaki",
        anime: "One-Punch Man",
        gender: "Female",
        hairColor: "Green",
        firstAppearanceYear: 2015,
    },
    // My Hero Academia (2016)
    {
        name: "Izuku Midoriya (Deku)",
        anime: "My Hero Academia",
        gender: "Male",
        hairColor: "Green",
        firstAppearanceYear: 2016,
    },
    {
        name: "Katsuki Bakugo",
        anime: "My Hero Academia",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2016,
    },
    {
        name: "Shoto Todoroki",
        anime: "My Hero Academia",
        gender: "Male",
        hairColor: "Red and White",
        firstAppearanceYear: 2016,
    },
    {
        name: "All Might (Toshinori Yagi)",
        anime: "My Hero Academia",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2016,
    },
    {
        name: "Ochaco Uraraka",
        anime: "My Hero Academia",
        gender: "Female",
        hairColor: "Brown",
        firstAppearanceYear: 2016,
    },
    {
        name: "Shota Aizawa (Eraser Head)",
        anime: "My Hero Academia",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2016,
    },
    {
        name: "Eijiro Kirishima",
        anime: "My Hero Academia",
        gender: "Male",
        hairColor: "Red",
        firstAppearanceYear: 2016,
    },
    {
        name: "Tomura Shigaraki",
        anime: "My Hero Academia",
        gender: "Male",
        hairColor: "Blue",
        firstAppearanceYear: 2016,
    },
    // Re:Zero (2016)
    {
        name: "Natsuki Subaru",
        anime: "Re:Zero",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2016,
    },
    {
        name: "Emilia",
        anime: "Re:Zero",
        gender: "Female",
        hairColor: "Silver",
        firstAppearanceYear: 2016,
    },
    {
        name: "Rem",
        anime: "Re:Zero",
        gender: "Female",
        hairColor: "Blue",
        firstAppearanceYear: 2016,
    },
    {
        name: "Ram",
        anime: "Re:Zero",
        gender: "Female",
        hairColor: "Pink",
        firstAppearanceYear: 2016,
    },
    // Bungo Stray Dogs (2016)
    {
        name: "Atsushi Nakajima",
        anime: "Bungo Stray Dogs",
        gender: "Male",
        hairColor: "White",
        firstAppearanceYear: 2016,
    },
    {
        name: "Osamu Dazai",
        anime: "Bungo Stray Dogs",
        gender: "Male",
        hairColor: "Brown",
        firstAppearanceYear: 2016,
    },
    {
        name: "Ryunosuke Akutagawa",
        anime: "Bungo Stray Dogs",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2016,
    },
    {
        name: "Chuya Nakahara",
        anime: "Bungo Stray Dogs",
        gender: "Male",
        hairColor: "Orange",
        firstAppearanceYear: 2016,
    },
    // Mob Psycho 100 (2016)
    {
        name: "Shigeo Kageyama (Mob)",
        anime: "Mob Psycho 100",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2016,
    },
    {
        name: "Arataka Reigen",
        anime: "Mob Psycho 100",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2016,
    },
    {
        name: "Dimple",
        anime: "Mob Psycho 100",
        gender: "Male",
        hairColor: "None",
        firstAppearanceYear: 2016,
    },
    // Black Clover (2017)
    {
        name: "Asta",
        anime: "Black Clover",
        gender: "Male",
        hairColor: "White",
        firstAppearanceYear: 2017,
    },
    {
        name: "Yuno Grinberryall",
        anime: "Black Clover",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2017,
    },
    {
        name: "Noelle Silva",
        anime: "Black Clover",
        gender: "Female",
        hairColor: "Silver",
        firstAppearanceYear: 2017,
    },
    {
        name: "Yami Sukehiro",
        anime: "Black Clover",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2017,
    },
    // Violet Evergarden (2018)
    {
        name: "Violet Evergarden",
        anime: "Violet Evergarden",
        gender: "Female",
        hairColor: "Blonde",
        firstAppearanceYear: 2018,
    },
    {
        name: "Gilbert Bougainvillea",
        anime: "Violet Evergarden",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2018,
    },
    // That Time I Got Reincarnated as a Slime (2018)
    {
        name: "Rimuru Tempest",
        anime: "That Time I Got Reincarnated as a Slime",
        gender: "Male",
        hairColor: "Blue",
        firstAppearanceYear: 2018,
    },
    {
        name: "Shizue Izawa",
        anime: "That Time I Got Reincarnated as a Slime",
        gender: "Female",
        hairColor: "Black",
        firstAppearanceYear: 2018,
    },
    {
        name: "Milim Nava",
        anime: "That Time I Got Reincarnated as a Slime",
        gender: "Female",
        hairColor: "Pink",
        firstAppearanceYear: 2018,
    },
    // Demon Slayer: Kimetsu no Yaiba (2019)
    {
        name: "Tanjiro Kamado",
        anime: "Demon Slayer: Kimetsu no Yaiba",
        gender: "Male",
        hairColor: "Red",
        firstAppearanceYear: 2019,
    },
    {
        name: "Nezuko Kamado",
        anime: "Demon Slayer: Kimetsu no Yaiba",
        gender: "Female",
        hairColor: "Black",
        firstAppearanceYear: 2019,
    },
    {
        name: "Zenitsu Agatsuma",
        anime: "Demon Slayer: Kimetsu no Yaiba",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2019,
    },
    {
        name: "Inosuke Hashibira",
        anime: "Demon Slayer: Kimetsu no Yaiba",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2019,
    },
    {
        name: "Giyu Tomioka",
        anime: "Demon Slayer: Kimetsu no Yaiba",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2019,
    },
    {
        name: "Shinobu Kocho",
        anime: "Demon Slayer: Kimetsu no Yaiba",
        gender: "Female",
        hairColor: "Black",
        firstAppearanceYear: 2019,
    },
    {
        name: "Kyojuro Rengoku",
        anime: "Demon Slayer: Kimetsu no Yaiba",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2019,
    },
    {
        name: "Muzan Kibutsuji",
        anime: "Demon Slayer: Kimetsu no Yaiba",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2019,
    },
    // Dr. Stone (2019)
    {
        name: "Senku Ishigami",
        anime: "Dr. Stone",
        gender: "Male",
        hairColor: "White",
        firstAppearanceYear: 2019,
    },
    {
        name: "Taiju Oki",
        anime: "Dr. Stone",
        gender: "Male",
        hairColor: "Brown",
        firstAppearanceYear: 2019,
    },
    {
        name: "Yuzuriha Ogawa",
        anime: "Dr. Stone",
        gender: "Female",
        hairColor: "Brown",
        firstAppearanceYear: 2019,
    },
    {
        name: "Kohaku",
        anime: "Dr. Stone",
        gender: "Female",
        hairColor: "Blonde",
        firstAppearanceYear: 2019,
    },
    // Vinland Saga (2019)
    {
        name: "Thorfinn",
        anime: "Vinland Saga",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2019,
    },
    {
        name: "Askeladd",
        anime: "Vinland Saga",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2019,
    },
    {
        name: "Canute",
        anime: "Vinland Saga",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2019,
    },
    // Kaguya-sama: Love Is War (2019)
    {
        name: "Kaguya Shinomiya",
        anime: "Kaguya-sama: Love Is War",
        gender: "Female",
        hairColor: "Black",
        firstAppearanceYear: 2019,
    },
    {
        name: "Miyuki Shirogane",
        anime: "Kaguya-sama: Love Is War",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2019,
    },
    {
        name: "Chika Fujiwara",
        anime: "Kaguya-sama: Love Is War",
        gender: "Female",
        hairColor: "Pink",
        firstAppearanceYear: 2019,
    },
    // Jujutsu Kaisen (2020)
    {
        name: "Yuji Itadori",
        anime: "Jujutsu Kaisen",
        gender: "Male",
        hairColor: "Pink",
        firstAppearanceYear: 2020,
    },
    {
        name: "Megumi Fushiguro",
        anime: "Jujutsu Kaisen",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2020,
    },
    {
        name: "Nobara Kugisaki",
        anime: "Jujutsu Kaisen",
        gender: "Female",
        hairColor: "Orange",
        firstAppearanceYear: 2020,
    },
    {
        name: "Satoru Gojo",
        anime: "Jujutsu Kaisen",
        gender: "Male",
        hairColor: "White",
        firstAppearanceYear: 2020,
    },
    {
        name: "Ryomen Sukuna",
        anime: "Jujutsu Kaisen",
        gender: "Male",
        hairColor: "Pink",
        firstAppearanceYear: 2020,
    },
    {
        name: "Kento Nanami",
        anime: "Jujutsu Kaisen",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2020,
    },
    {
        name: "Toge Inumaki",
        anime: "Jujutsu Kaisen",
        gender: "Male",
        hairColor: "White",
        firstAppearanceYear: 2020,
    },
    {
        name: "Maki Zenin",
        anime: "Jujutsu Kaisen",
        gender: "Female",
        hairColor: "Green",
        firstAppearanceYear: 2020,
    },
    // Tokyo Revengers (2021)
    {
        name: "Takemichi Hanagaki",
        anime: "Tokyo Revengers",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2021,
    },
    {
        name: "Manjiro Sano (Mikey)",
        anime: "Tokyo Revengers",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2021,
    },
    {
        name: "Ken Ryuguji (Draken)",
        anime: "Tokyo Revengers",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2021,
    },
    // Mushoku Tensei: Jobless Reincarnation (2021)
    {
        name: "Rudeus Greyrat",
        anime: "Mushoku Tensei: Jobless Reincarnation",
        gender: "Male",
        hairColor: "Brown",
        firstAppearanceYear: 2021,
    },
    {
        name: "Eris Boreas Greyrat",
        anime: "Mushoku Tensei: Jobless Reincarnation",
        gender: "Female",
        hairColor: "Red",
        firstAppearanceYear: 2021,
    },
    {
        name: "Roxy Migurdia",
        anime: "Mushoku Tensei: Jobless Reincarnation",
        gender: "Female",
        hairColor: "Blue",
        firstAppearanceYear: 2021,
    },
    // Spy x Family (2022)
    {
        name: "Loid Forger",
        anime: "Spy x Family",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2022,
    },
    {
        name: "Yor Forger",
        anime: "Spy x Family",
        gender: "Female",
        hairColor: "Black",
        firstAppearanceYear: 2022,
    },
    {
        name: "Anya Forger",
        anime: "Spy x Family",
        gender: "Female",
        hairColor: "Pink",
        firstAppearanceYear: 2022,
    },
    // Chainsaw Man (2022)
    {
        name: "Denji",
        anime: "Chainsaw Man",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2022,
    },
    {
        name: "Makima",
        anime: "Chainsaw Man",
        gender: "Female",
        hairColor: "Red",
        firstAppearanceYear: 2022,
    },
    {
        name: "Power",
        anime: "Chainsaw Man",
        gender: "Female",
        hairColor: "Blonde",
        firstAppearanceYear: 2022,
    },
    {
        name: "Aki Hayakawa",
        anime: "Chainsaw Man",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2022,
    },
    // Bocchi the Rock! (2022)
    {
        name: "Hitori Gotoh (Bocchi)",
        anime: "Bocchi the Rock!",
        gender: "Female",
        hairColor: "Pink",
        firstAppearanceYear: 2022,
    },
    {
        name: "Nijika Ijichi",
        anime: "Bocchi the Rock!",
        gender: "Female",
        hairColor: "Blonde",
        firstAppearanceYear: 2022,
    },
    {
        name: "Ryo Yamada",
        anime: "Bocchi the Rock!",
        gender: "Female",
        hairColor: "Blue",
        firstAppearanceYear: 2022,
    },
    // Oshi no Ko (2023)
    {
        name: "Ai Hoshino",
        anime: "Oshi no Ko",
        gender: "Female",
        hairColor: "Purple",
        firstAppearanceYear: 2023,
    },
    {
        name: "Aquamarine Hoshino",
        anime: "Oshi no Ko",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2023,
    },
    {
        name: "Ruby Hoshino",
        anime: "Oshi no Ko",
        gender: "Female",
        hairColor: "Blonde",
        firstAppearanceYear: 2023,
    },
    {
        name: "Kana Arima",
        anime: "Oshi no Ko",
        gender: "Female",
        hairColor: "Red",
        firstAppearanceYear: 2023,
    },
    // Frieren: Beyond Journey's End (2023)
    {
        name: "Frieren",
        anime: "Frieren: Beyond Journey's End",
        gender: "Female",
        hairColor: "White",
        firstAppearanceYear: 2023,
    },
    {
        name: "Fern",
        anime: "Frieren: Beyond Journey's End",
        gender: "Female",
        hairColor: "Purple",
        firstAppearanceYear: 2023,
    },
    {
        name: "Stark",
        anime: "Frieren: Beyond Journey's End",
        gender: "Male",
        hairColor: "Red",
        firstAppearanceYear: 2023,
    },
    {
        name: "Himmel",
        anime: "Frieren: Beyond Journey's End",
        gender: "Male",
        hairColor: "Blue",
        firstAppearanceYear: 2023,
    },
    // เพิ่มเติมเพื่อครบ 450 - More Characters from Popular Series
    // Naruto - Akatsuki & More
    {
        name: "Pain (Nagato)",
        anime: "Naruto Shippuden",
        gender: "Male",
        hairColor: "Red",
        firstAppearanceYear: 2007,
    },
    {
        name: "Konan",
        anime: "Naruto Shippuden",
        gender: "Female",
        hairColor: "Blue",
        firstAppearanceYear: 2007,
    },
    {
        name: "Deidara",
        anime: "Naruto Shippuden",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2007,
    },
    {
        name: "Sasori",
        anime: "Naruto Shippuden",
        gender: "Male",
        hairColor: "Red",
        firstAppearanceYear: 2007,
    },
    {
        name: "Kisame Hoshigaki",
        anime: "Naruto",
        gender: "Male",
        hairColor: "Blue",
        firstAppearanceYear: 2002,
    },
    {
        name: "Minato Namikaze",
        anime: "Naruto Shippuden",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2007,
    },
    {
        name: "Might Guy",
        anime: "Naruto",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2002,
    },
    {
        name: "Neji Hyuga",
        anime: "Naruto",
        gender: "Male",
        hairColor: "Brown",
        firstAppearanceYear: 2002,
    },
    {
        name: "Tsunade",
        anime: "Naruto",
        gender: "Female",
        hairColor: "Blonde",
        firstAppearanceYear: 2002,
    },
    // One Piece - More Crew and Villains
    {
        name: "Donquixote Doflamingo",
        anime: "One Piece",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 1999,
    },
    {
        name: "Crocodile",
        anime: "One Piece",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 1999,
    },
    {
        name: "Charlotte Katakuri",
        anime: "One Piece",
        gender: "Male",
        hairColor: "Red",
        firstAppearanceYear: 1999,
    },
    {
        name: "Sabo",
        anime: "One Piece",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 1999,
    },
    {
        name: "Yamato",
        anime: "One Piece",
        gender: "Female",
        hairColor: "White",
        firstAppearanceYear: 1999,
    },
    {
        name: "Eustass Kid",
        anime: "One Piece",
        gender: "Male",
        hairColor: "Red",
        firstAppearanceYear: 1999,
    },
    {
        name: "Marshall D. Teach (Blackbeard)",
        anime: "One Piece",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 1999,
    },
    {
        name: "Akainu (Sakazuki)",
        anime: "One Piece",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 1999,
    },
    // Bleach - More Captains & Espada
    {
        name: "Genryusai Shigekuni Yamamoto",
        anime: "Bleach",
        gender: "Male",
        hairColor: "White",
        firstAppearanceYear: 2004,
    },
    {
        name: "Gin Ichimaru",
        anime: "Bleach",
        gender: "Male",
        hairColor: "Silver",
        firstAppearanceYear: 2004,
    },
    {
        name: "Shunsui Kyoraku",
        anime: "Bleach",
        gender: "Male",
        hairColor: "Brown",
        firstAppearanceYear: 2004,
    },
    {
        name: "Yoruichi Shihoin",
        anime: "Bleach",
        gender: "Female",
        hairColor: "Purple",
        firstAppearanceYear: 2004,
    },
    {
        name: "Kisuke Urahara",
        anime: "Bleach",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2004,
    },
    {
        name: "Nelliel Tu Odelschwanck",
        anime: "Bleach",
        gender: "Female",
        hairColor: "Green",
        firstAppearanceYear: 2004,
    },
    // Attack on Titan - More Survey Corps
    {
        name: "Jean Kirstein",
        anime: "Attack on Titan",
        gender: "Male",
        hairColor: "Brown",
        firstAppearanceYear: 2013,
    },
    {
        name: "Connie Springer",
        anime: "Attack on Titan",
        gender: "Male",
        hairColor: "White",
        firstAppearanceYear: 2013,
    },
    {
        name: "Historia Reiss",
        anime: "Attack on Titan",
        gender: "Female",
        hairColor: "Blonde",
        firstAppearanceYear: 2013,
    },
    {
        name: "Annie Leonhart",
        anime: "Attack on Titan",
        gender: "Female",
        hairColor: "Blonde",
        firstAppearanceYear: 2013,
    },
    {
        name: "Zeke Yeager",
        anime: "Attack on Titan",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2013,
    },
    // My Hero Academia - More Students & Villains
    {
        name: "Tenya Iida",
        anime: "My Hero Academia",
        gender: "Male",
        hairColor: "Blue",
        firstAppearanceYear: 2016,
    },
    {
        name: "Momo Yaoyorozu",
        anime: "My Hero Academia",
        gender: "Female",
        hairColor: "Black",
        firstAppearanceYear: 2016,
    },
    {
        name: "Dabi (Toya Todoroki)",
        anime: "My Hero Academia",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2016,
    },
    {
        name: "Himiko Toga",
        anime: "My Hero Academia",
        gender: "Female",
        hairColor: "Blonde",
        firstAppearanceYear: 2016,
    },
    {
        name: "Hawks (Keigo Takami)",
        anime: "My Hero Academia",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2016,
    },
    // Fate Series (based on popular anime adaptations)
    // Fate/stay night: Unlimited Blade Works (2014)
    {
        name: "Shirou Emiya",
        anime: "Fate/stay night: Unlimited Blade Works",
        gender: "Male",
        hairColor: "Red",
        firstAppearanceYear: 2014,
    },
    {
        name: "Saber (Artoria Pendragon)",
        anime: "Fate/stay night: Unlimited Blade Works",
        gender: "Female",
        hairColor: "Blonde",
        firstAppearanceYear: 2014,
    },
    {
        name: "Rin Tohsaka",
        anime: "Fate/stay night: Unlimited Blade Works",
        gender: "Female",
        hairColor: "Black",
        firstAppearanceYear: 2014,
    },
    {
        name: "Archer (EMIYA)",
        anime: "Fate/stay night: Unlimited Blade Works",
        gender: "Male",
        hairColor: "White",
        firstAppearanceYear: 2014,
    },
    {
        name: "Gilgamesh",
        anime: "Fate/stay night: Unlimited Blade Works",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2014,
    },
    // Fate/Zero (2011)
    {
        name: "Kiritsugu Emiya",
        anime: "Fate/Zero",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2011,
    },
    {
        name: "Irisviel von Einzbern",
        anime: "Fate/Zero",
        gender: "Female",
        hairColor: "White",
        firstAppearanceYear: 2011,
    },
    {
        name: "Kirei Kotomine",
        anime: "Fate/Zero",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2011,
    },
    {
        name: "Rider (Iskandar)",
        anime: "Fate/Zero",
        gender: "Male",
        hairColor: "Red",
        firstAppearanceYear: 2011,
    },
    // More Classics & Popular Shows
    // Trigun (1998)
    {
        name: "Vash the Stampede",
        anime: "Trigun",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 1998,
    },
    {
        name: "Nicholas D. Wolfwood",
        anime: "Trigun",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 1998,
    },
    // Berserk (1997)
    {
        name: "Guts",
        anime: "Berserk",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 1997,
    },
    {
        name: "Griffith",
        anime: "Berserk",
        gender: "Male",
        hairColor: "White",
        firstAppearanceYear: 1997,
    },
    {
        name: "Casca",
        anime: "Berserk",
        gender: "Female",
        hairColor: "Black",
        firstAppearanceYear: 1997,
    },
    // Fullmetal Alchemist: Brotherhood (2009)
    {
        name: "Ling Yao",
        anime: "Fullmetal Alchemist: Brotherhood",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2009,
    },
    {
        name: "Olivier Mira Armstrong",
        anime: "Fullmetal Alchemist: Brotherhood",
        gender: "Female",
        hairColor: "Blonde",
        firstAppearanceYear: 2009,
    },
    {
        name: "Scar",
        anime: "Fullmetal Alchemist: Brotherhood",
        gender: "Male",
        hairColor: "White",
        firstAppearanceYear: 2009,
    },
    // Psycho-Pass (2012)
    {
        name: "Shinya Kogami",
        anime: "Psycho-Pass",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2012,
    },
    {
        name: "Akane Tsunemori",
        anime: "Psycho-Pass",
        gender: "Female",
        hairColor: "Brown",
        firstAppearanceYear: 2012,
    },
    {
        name: "Shogo Makishima",
        anime: "Psycho-Pass",
        gender: "Male",
        hairColor: "White",
        firstAppearanceYear: 2012,
    },
    // Kill la Kill (2013)
    {
        name: "Ryuko Matoi",
        anime: "Kill la Kill",
        gender: "Female",
        hairColor: "Black",
        firstAppearanceYear: 2013,
    },
    {
        name: "Satsuki Kiryuin",
        anime: "Kill la Kill",
        gender: "Female",
        hairColor: "Black",
        firstAppearanceYear: 2013,
    },
    {
        name: "Mako Mankanshoku",
        anime: "Kill la Kill",
        gender: "Female",
        hairColor: "Brown",
        firstAppearanceYear: 2013,
    },
    // Noragami (2014)
    {
        name: "Yato",
        anime: "Noragami",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2014,
    },
    {
        name: "Hiyori Iki",
        anime: "Noragami",
        gender: "Female",
        hairColor: "Brown",
        firstAppearanceYear: 2014,
    },
    // KonoSuba (2016)
    {
        name: "Kazuma Sato",
        anime: "KonoSuba",
        gender: "Male",
        hairColor: "Brown",
        firstAppearanceYear: 2016,
    },
    {
        name: "Aqua",
        anime: "KonoSuba",
        gender: "Female",
        hairColor: "Blue",
        firstAppearanceYear: 2016,
    },
    {
        name: "Megumin",
        anime: "KonoSuba",
        gender: "Female",
        hairColor: "Black",
        firstAppearanceYear: 2016,
    },
    {
        name: "Darkness (Lalatina)",
        anime: "KonoSuba",
        gender: "Female",
        hairColor: "Blonde",
        firstAppearanceYear: 2016,
    },
    // The Promised Neverland (2019)
    {
        name: "Emma",
        anime: "The Promised Neverland",
        gender: "Female",
        hairColor: "Orange",
        firstAppearanceYear: 2019,
    },
    {
        name: "Norman",
        anime: "The Promised Neverland",
        gender: "Male",
        hairColor: "White",
        firstAppearanceYear: 2019,
    },
    {
        name: "Ray",
        anime: "The Promised Neverland",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2019,
    },
    // Fire Force (2019)
    {
        name: "Shinra Kusakabe",
        anime: "Fire Force",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2019,
    },
    {
        name: "Arthur Boyle",
        anime: "Fire Force",
        gender: "Male",
        hairColor: "Blonde",
        firstAppearanceYear: 2019,
    },
    {
        name: "Maki Oze",
        anime: "Fire Force",
        gender: "Female",
        hairColor: "Black",
        firstAppearanceYear: 2019,
    },
    // Horimiya (2021)
    {
        name: "Kyoko Hori",
        anime: "Horimiya",
        gender: "Female",
        hairColor: "Brown",
        firstAppearanceYear: 2021,
    },
    {
        name: "Izumi Miyamura",
        anime: "Horimiya",
        gender: "Male",
        hairColor: "Black",
        firstAppearanceYear: 2021,
    },
    // Cyberpunk: Edgerunners (2022)
    {
        name: "David Martinez",
        anime: "Cyberpunk: Edgerunners",
        gender: "Male",
        hairColor: "Brown",
        firstAppearanceYear: 2022,
    },
    {
        name: "Lucy",
        anime: "Cyberpunk: Edgerunners",
        gender: "Female",
        hairColor: "White",
        firstAppearanceYear: 2022,
    },
    {
        name: "Rebecca",
        anime: "Cyberpunk: Edgerunners",
        gender: "Female",
        hairColor: "White",
        firstAppearanceYear: 2022,
    },
];
